---
# tasks file for common
- name: install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open ssh port
  command: ufw allow 22/tcp
  when: not ufw_status_result.stdout is search("22/tcp.*ALLOW IN.*Anywhere")

- name: open vpn port
  command: ufw allow {{ vpn_port }}/udp
  when: not ufw_status_result.stdout is search(vpn_port ~ "/udp.*ALLOW IN.*Anywhere")

- debug:
    msg:
      - "ufw_status_result.stdout: {{ ufw_status_result.stdout }}"
      - "p2p_port: {{ p2p_port }}"
      - "inventory_hostname: {{ inventory_hostname }}"
      - "groups['public']: {{ groups['public'] }}"

- name: open p2p port
  command: ufw allow {{ p2p_port }}/tcp
  when: (not ufw_status_result.stdout is search(p2p_port ~ "/tcp.*ALLOW IN.*Anywhere")) and
        (inventory_hostname in groups['public'])

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")
