---
# tasks file for common
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    uid: 1000
    group: polkadot
    append: yes

- name: download polkadot binary
  get_url:
    url: https://github.com/w3f/polkadot-deployer/releases/download/k4a/polkadot
    dest: /usr/local/bin/polkadot
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'
