---
# tasks file for polkadot
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    group: polkadot
    append: yes

- name: download polkadot binary
  get_url:
    url: '{{ polkadot_binary_url | quote }}'
    checksum: '{{ polkadot_binary_checksum | quote }}'
    dest: /usr/local/bin/polkadot
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'
