---
- name: create VPN configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
    validate: "bash -c 'test ! -f /etc/wireguard/wg0.conf' || bash -c 'test ! diff -q %s /etc/wireguard/wg0.conf'"

- name: start VPN setup service
  systemd:
    name: wg-quick@wg0
    state: started
  notify: enable VPN setup service
