---
- name: check if config already exists
  stat:
    path: /etc/wireguard/wg0.conf
  register: vpn_cfg

- name: create VPN configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  when: not vpn_cfg.stat.exists

- name: start VPN setup service
  systemd:
    name: wg-quick@wg0
    state: started
  notify: enable VPN setup service
