---
- name: install gpg
  apt:
    name: gpg
    state: present

- name: add vpncloud apt-key
  apt_key:
    url: https://repo.ddswd.de/deb/public.key
    state: present

- name: add vpncloud repo
  apt_repository:
    repo: deb https://repo.ddswd.de/deb stable main
    state: present

- name: install vpncloud
  apt:
    name: vpncloud
    update_cache: yes

- name: create VPN configuration file
  template:
    src: vpncloud.default.net.j2
    dest: /etc/vpncloud/default.net
    owner: root
    group: root
    mode: 0600

- name: start vpncloud service
  systemd:
    name: vpncloud@default
    state: started
  notify: enable vpncloud service
