---
- name: create VPN configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: start VPN service
  systemd:
    name: wg-quick@wg0
    state: started
  notify: enable VPN service
