---
# tasks file for vpnpeer-setup
- name: get linux version
  command: uname -r
  register: uname

- name: install linux-headers
  apt:
    name: linux-headers-{{ uname.stdout }}
    update_cache: yes

- name: add wireguard repo
  apt_repository:
    repo: ppa:wireguard/wireguard
    state: present

- name: install wireguard
  apt:
    name: wireguard

- name: check if config already exists
  stat:
    path: /etc/wireguard/wg0.conf
  register: vpn_cfg

- name: generate wireguard private key
  command: wg genkey
  register: private_key
  when: not vpn_cfg.stat.exists

- name: generate wireguard public key
  command: wg pubkey
  args:
    stdin: "{{ private_key.stdout }}"
  register: public_key
  when: not vpn_cfg.stat.exists

- name: save public_key as host fact
  set_fact:
    vpn_public_key: "{{ public_key.stdout }}"
  when: not vpn_cfg.stat.exists
