- hosts: all
  become: yes
  roles:
  - common
  - vpnpeer-setup
  - vpnpeer
  - polkadot-common

- hosts: public
  become: yes
  roles:
  - polkadot-public

- hosts: validator
  become: yes
  roles:
  - polkadot-validator
